import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLang = localStorage.getItem('language');
    return savedLang || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  // Traductions
  const translations = {
    en: {
      // Navbar
      home: 'Home',
      menu: 'Menu',
      promotions: 'Promotions',
      contact: 'Contact',
      login: 'Login',
      logout: 'Logout',
      // Hero
      welcome: 'Welcome to Flavor House',
      restaurant: 'RESTAURANT',
      description: 'Delicious Moments for Every Taste — Experience culinary excellence crafted with passion and flair.',
      orderNow: 'Order Now →',
      exploreMenu: 'Explore Menu',
      // Menu
      ourMenu: 'Our Menu',
      discover: 'Discover our delicious dishes',
      add: 'Add',
      // Dans en:
      search: 'Search',
      advancedSearch: 'Advanced Search',
      searchByName: 'Search by name...',
      searchByCategory: 'Category',
      searchByPrice: 'Price Range',
      searchByIngredients: 'Ingredients',
      resetFilters: 'Reset Filters',
      results: 'results',
      noResults: 'No results found',
      tryAdjusting: 'Try adjusting your filters',

      // Dans fr:
      search: 'Recherche',
      advancedSearch: 'Recherche avancée',
      searchByName: 'Rechercher par nom...',
      searchByCategory: 'Catégorie',
      searchByPrice: 'Prix',
      searchByIngredients: 'Ingrédients',
      resetFilters: 'Réinitialiser',
      results: 'résultats',
      noResults: 'Aucun résultat trouvé',
      tryAdjusting: 'Essayez d\'ajuster vos filtres',

      // Dans ar:
      search: 'بحث',
      advancedSearch: 'بحث متقدم',
      searchByName: 'البحث بالاسم...',
      searchByCategory: 'الفئة',
      searchByPrice: 'السعر',
      searchByIngredients: 'المكونات',
      resetFilters: 'إعادة تعيين',
      results: 'نتائج',
      noResults: 'لا توجد نتائج',
      tryAdjusting: 'حاول تعديل الفلاتر',
      // Cart
      yourCart: 'Your Cart',
      items: 'items',
      emptyCart: 'Your cart is empty',
      addSomeFood: 'Add some delicious food!',
      browseMenu: 'Browse Menu',
      orderSummary: 'Order Summary',
      subtotal: 'Subtotal',
      deliveryFee: 'Delivery Fee',
      total: 'Total',
      delivery: 'Delivery',
      pickup: 'Pickup',
      fullName: 'Full Name',
      phoneNumber: 'Phone Number',
      deliveryAddress: 'Delivery Address',
      location: 'Location (Google Maps link)',
      proceedToCheckout: 'Proceed to Checkout',
      payOnline: 'Pay Online',
      // Login
      welcomeBack: 'Welcome Back!',
      loginToAccount: 'Login to your account',
      emailAddress: 'Email Address',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      createAccount: 'Create Account',
      joinToday: 'Join Flavor House today',
      signUp: 'Sign Up',
      or: 'OR',
      continueWithGoogle: 'Continue with Google',
      continueWithFacebook: 'Continue with Facebook',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      demoCredentials: 'Demo: admin@flavorhouse.dz / admin123',
      driverCredentials: 'Driver: driver@flavorhouse.dz / driver123',
      // Favorites
      yourFavorites: 'Your Favorites',
      noFavorites: 'No favorites yet',
      startAdding: 'Start adding your favorite dishes!',
      // Promotions
      promotionsTitle: 'Promotions',
      specialOffers: 'Special offers just for you!',
      copyCode: 'Copy',
      validUntil: 'Valid until',
      // Contact
      contactUs: 'Contact Us',
      weAreHere: 'We are here to help you!',
      getInTouch: 'Get in Touch',
      phone: 'Phone',
      whatsapp: 'WhatsApp',
      email: 'Email',
      address: 'Address',
      openingHours: 'Opening Hours',
      sendMessage: 'Send Message',
      subject: 'Subject',
      message: 'Message',
      // Admin
      admin: 'Admin',
      dashboard: 'Dashboard',
      totalOrders: 'Total Orders',
      revenue: 'Revenue',
      products: 'Products',
      customers: 'Customers',
      recentOrders: 'Recent Orders',
      view: 'View',
      addProduct: 'Add Product',
      edit: 'Edit',
      delete: 'Delete',
      saveProduct: 'Save Product',
      cancel: 'Cancel',
      // Driver
      driver: 'Driver',
      assignedOrders: 'Assigned Orders',
      inProgress: 'In Progress',
      delivered: 'Delivered',
      callCustomer: 'Call Customer',
      startDelivery: 'Start Delivery',
      markAsDelivered: 'Mark as Delivered',
      online: 'Online',
    },
    fr: {
      home: 'Accueil',
      menu: 'Menu',
      promotions: 'Promotions',
      contact: 'Contact',
      login: 'Se connecter',
      logout: 'Se déconnecter',
      welcome: 'Bienvenue chez Flavor House',
      restaurant: 'RESTAURANT',
      description: 'Des moments délicieux pour chaque goût — Découvrez une excellence culinaire faite avec passion et flair.',
      orderNow: 'Commander →',
      exploreMenu: 'Explorer le menu',
      ourMenu: 'Notre Menu',
      discover: 'Découvrez nos plats délicieux',
      add: 'Ajouter',
      yourCart: 'Votre Panier',
      items: 'articles',
      emptyCart: 'Votre panier est vide',
      addSomeFood: 'Ajoutez de délicieux plats !',
      browseMenu: 'Parcourir le menu',
      orderSummary: 'Résumé de la commande',
      subtotal: 'Sous-total',
      deliveryFee: 'Frais de livraison',
      total: 'Total',
      delivery: 'Livraison',
      pickup: 'À emporter',
      fullName: 'Nom complet',
      phoneNumber: 'Numéro de téléphone',
      deliveryAddress: 'Adresse de livraison',
      location: 'Adresse (lien Google Maps)',
      proceedToCheckout: 'Passer à la caisse',
      payOnline: 'Payer en ligne',
      welcomeBack: 'Bon retour !',
      loginToAccount: 'Connectez-vous à votre compte',
      emailAddress: 'Adresse e-mail',
      password: 'Mot de passe',
      forgotPassword: 'Mot de passe oublié ?',
      createAccount: 'Créer un compte',
      joinToday: 'Rejoignez Flavor House aujourd\'hui',
      signUp: "S'inscrire",
      or: 'OU',
      continueWithGoogle: 'Continuer avec Google',
      continueWithFacebook: 'Continuer avec Facebook',
      dontHaveAccount: "Vous n'avez pas de compte ?",
      alreadyHaveAccount: 'Vous avez déjà un compte ?',
      demoCredentials: 'Démo: admin@flavorhouse.dz / admin123',
      driverCredentials: 'Livreur: driver@flavorhouse.dz / driver123',
      yourFavorites: 'Vos Favoris',
      noFavorites: 'Pas encore de favoris',
      startAdding: 'Commencez à ajouter vos plats préférés !',
      promotionsTitle: 'Promotions',
      specialOffers: 'Des offres spéciales pour vous !',
      copyCode: 'Copier',
      validUntil: 'Valable jusqu\'au',
      contactUs: 'Contactez-nous',
      weAreHere: 'Nous sommes là pour vous aider !',
      getInTouch: 'Contactez-nous',
      phone: 'Téléphone',
      whatsapp: 'WhatsApp',
      email: 'E-mail',
      address: 'Adresse',
      openingHours: 'Horaires d\'ouverture',
      sendMessage: 'Envoyer le message',
      subject: 'Sujet',
      message: 'Message',
      admin: 'Admin',
      dashboard: 'Tableau de bord',
      totalOrders: 'Commandes totales',
      revenue: 'Revenus',
      products: 'Produits',
      customers: 'Clients',
      recentOrders: 'Commandes récentes',
      view: 'Voir',
      addProduct: 'Ajouter un produit',
      edit: 'Modifier',
      delete: 'Supprimer',
      saveProduct: 'Enregistrer',
      cancel: 'Annuler',
      driver: 'Livreur',
      assignedOrders: 'Commandes assignées',
      inProgress: 'En cours',
      delivered: 'Livré',
      callCustomer: 'Appeler le client',
      startDelivery: 'Démarrer la livraison',
      markAsDelivered: 'Marquer comme livré',
      online: 'En ligne',
    },
    ar: {
      home: 'الرئيسية',
      menu: 'القائمة',
      promotions: 'العروض',
      contact: 'اتصل بنا',
      login: 'تسجيل الدخول',
      logout: 'تسجيل الخروج',
      welcome: 'مرحباً بكم في فلافور هاوس',
      restaurant: 'مطعم',
      description: 'لحظات لذيذة لكل الأذواق — اكتشفوا التميز الطهوي المصنوع بشغف وأناقة.',
      orderNow: 'اطلب الآن →',
      exploreMenu: 'استكشف القائمة',
      ourMenu: 'قائمتنا',
      discover: 'اكتشف أطباقنا اللذيذة',
      add: 'أضف',
      yourCart: 'سلة التسوق',
      items: 'عناصر',
      emptyCart: 'سلة التسوق فارغة',
      addSomeFood: 'أضف بعض الأطباق اللذيذة!',
      browseMenu: 'تصفح القائمة',
      orderSummary: 'ملخص الطلب',
      subtotal: 'المجموع الفرعي',
      deliveryFee: 'رسوم التوصيل',
      total: 'المجموع',
      delivery: 'توصيل',
      pickup: 'استلام',
      fullName: 'الاسم الكامل',
      phoneNumber: 'رقم الهاتف',
      deliveryAddress: 'عنوان التوصيل',
      location: 'الموقع (رابط خرائط جوجل)',
      proceedToCheckout: 'المتابعة للدفع',
      payOnline: 'الدفع عبر الإنترنت',
      welcomeBack: 'مرحباً بعودتك!',
      loginToAccount: 'تسجيل الدخول إلى حسابك',
      emailAddress: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      forgotPassword: 'نسيت كلمة المرور؟',
      createAccount: 'إنشاء حساب',
      joinToday: 'انضم إلى فلافور هاوس اليوم',
      signUp: 'اشتراك',
      or: 'أو',
      continueWithGoogle: 'المتابعة عبر جوجل',
      continueWithFacebook: 'المتابعة عبر فيسبوك',
      dontHaveAccount: 'ليس لديك حساب؟',
      alreadyHaveAccount: 'لديك حساب بالفعل؟',
      demoCredentials: 'تجريبي: admin@flavorhouse.dz / admin123',
      driverCredentials: 'سائق: driver@flavorhouse.dz / driver123',
      yourFavorites: 'المفضلة',
      noFavorites: 'لا توجد مفضلات بعد',
      startAdding: 'ابدأ بإضافة أطباقك المفضلة!',
      promotionsTitle: 'العروض',
      specialOffers: 'عروض خاصة لك!',
      copyCode: 'نسخ',
      validUntil: 'صالح حتى',
      contactUs: 'اتصل بنا',
      weAreHere: 'نحن هنا لمساعدتك!',
      getInTouch: 'تواصل معنا',
      phone: 'الهاتف',
      whatsapp: 'واتساب',
      email: 'البريد الإلكتروني',
      address: 'العنوان',
      openingHours: 'ساعات العمل',
      sendMessage: 'إرسال الرسالة',
      subject: 'الموضوع',
      message: 'الرسالة',
      admin: 'المشرف',
      dashboard: 'لوحة التحكم',
      totalOrders: 'إجمالي الطلبات',
      revenue: 'الإيرادات',
      products: 'المنتجات',
      customers: 'العملاء',
      recentOrders: 'الطلبات الأخيرة',
      view: 'عرض',
      addProduct: 'إضافة منتج',
      edit: 'تعديل',
      delete: 'حذف',
      saveProduct: 'حفظ',
      cancel: 'إلغاء',
      driver: 'السائق',
      assignedOrders: 'الطلبات المخصصة',
      inProgress: 'قيد التقدم',
      delivered: 'تم التوصيل',
      callCustomer: 'اتصال بالعميل',
      startDelivery: 'بدء التوصيل',
      markAsDelivered: 'تحديد كمُسلّم',
      online: 'متصل',
    }
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
